name: Deploy Rails app to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
            # Ensure RVM is sourced if it's used
            if [[ -s "/etc/profile.d/rvm.sh" ]]; then
              source /etc/profile.d/rvm.sh
            fi

            export RAILS_ENV=production
            export SECRET_KEY_BASE=$(rails secret)

            cd ${{ secrets.DEPLOYMENT_DIR }}

            # Pull latest code
            git pull origin main

            # Install dependencies
            bundle install --deployment --without development test

            # Run migrations
            rake db:migrate RAILS_ENV=production

            # Precompile assets
            bin/rails assets:precompile RAILS_ENV=production

            # Start/restart Puma (if systemd service is set up)
            if systemctl is-active --quiet puma; then
              sudo systemctl restart puma
            else
              sudo systemctl start puma
            fi
          EOF

      - name: Clean up SSH key
        run: rm -f ~/.ssh/id_rsa


